version: "3.9"

# Minimal setup with just database services
# Use this to get started quickly while building other services

services:
  # Database layer - starts first
  postgres:
    image: postgres:15-alpine
    container_name: recovery-compass-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-recovery_compass}
      POSTGRES_USER: ${POSTGRES_USER:-recovery_compass}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - core-net
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-recovery_compass}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Cache layer
  redis:
    image: redis:7-alpine
    container_name: recovery-compass-redis
    command: redis-server --requirepass ${REDIS_PASSWORD:-changeme}
    volumes:
      - redis-data:/data
    networks:
      - core-net
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  core-net:
    driver: bridge
    name: recovery-compass-core

volumes:
  postgres-data:
    name: recovery-compass-postgres-data
  redis-data:
    name: recovery-compass-redis-data
