repos:
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.40.0
    hooks:
      - id: markdownlint
        args: [--disable, MD013]   # example width rule only
        stages: [pre-commit]       # read-only lint, no --fix
  - repo: https://github.com/errata-ai/vale
    rev: v3.8.0
    hooks:
      - id: vale
        language: system          # uses pre-installed binary
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.7.0
    hooks:
      - id: cspell
        args: [--no-must-find-files]
