# Pre-commit hooks for Recovery Compass
# Ensures alignment tests pass before any commit

repos:
  - repo: local
    hooks:
      - id: alignment-tests
        name: Run alignment tests
        entry: npm run test
        language: system
        pass_filenames: false
        always_run: true

      - id: abundance-linter
        name: Check for urgency language
        entry: scripts/abundance_linter.py
        language: python
        files: '\.(md|yml|yaml|txt)$'
        exclude: '^(node_modules|.git|coverage|dist|build)/'

      - id: context-freshness
        name: Verify context freshness
        entry: scripts/check_context_freshness.py
        language: python
        pass_filenames: false
        always_run: true

      - id: metrics-threshold
        name: Check metrics thresholds
        entry: python scripts/check_thresholds.py 0.90 60 HIGH
        language: system
        pass_filenames: false
        always_run: true
