name: Docker Security Scan

on:
  push:
    branches: [ main ]
    paths:
      - '**/Dockerfile'
      - '**/docker-compose*.yml'
      - '.github/workflows/docker-security.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**/Dockerfile'
      - '**/docker-compose*.yml'
  schedule:
    - cron: '0 0 * * 1'  # Weekly scan on Mondays

jobs:
  trivy-scan:
    name: Trivy Security Scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner in repo mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

    - name: Run Trivy in GitHub PR comment mode
      uses: aquasecurity/trivy-action@master
      if: github.event_name == 'pull_request'
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'table'
        exit-code: '1'
        severity: 'CRITICAL,HIGH,MEDIUM'

  # This job will run when we have Docker images
  docker-image-scan:
    name: Scan Docker Images
    runs-on: ubuntu-latest
    if: false  # Enable when Docker images exist
    strategy:
      matrix:
        image:
          - funding-engine
          - erd-platform
          - metrics-relay
          - partner-portal
    steps:
    - name: Run Trivy on Docker image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'recovery-compass/${{ matrix.image }}:latest'
        format: 'sarif'
        output: 'trivy-${{ matrix.image }}.sarif'

    - name: Upload results
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-${{ matrix.image }}.sarif'
