name: markdown-lint-full
on:
  schedule:
    # Run every Sunday at 4 AM UTC
    - cron: "0 4 * * 0"
  workflow_dispatch: # Allow manual trigger

jobs:
  md-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json', '**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Run full repository markdown lint
        run: |
          echo "📋 Running full repository markdown lint..."
          npx markdownlint "**/*.md" --config .markdownlint.json --ignore node_modules --ignore venv

      - name: Create issue on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const title = 'Weekly Markdown Lint Check Failed';
            const body = `The weekly full-repository markdown lint check has failed.

            Please review the [workflow run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.

            This is an automated issue created by the scheduled markdown lint workflow.`;

            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              labels: ['documentation', 'automated']
            });
