name: Automated Security Remediation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 */4 * * *'  # Run every 4 hours
  workflow_dispatch:

jobs:
  security-remediation:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      security-events: write

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Run Automated Security Bot
      run: |
        python scripts/automated_security_remediation.py --github-action

    - name: Create Pull Request
      if: github.event_name != 'pull_request'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: '🔒 Automated security fixes'
        title: '🔒 [Security Bot] Automated vulnerability remediation'
        body: |
          ## 🤖 Automated Security Remediation

          This PR was automatically generated by the Recovery Compass Security Bot.

          ### Changes Made:
          - Updated vulnerable dependencies
          - Applied security overrides
          - Fixed critical vulnerabilities

          ### Security Status:
          - All vulnerabilities have been addressed
          - Runtime protections are in place
          - Continuous monitoring is active

          Auto-merge enabled for security fixes.
        branch: security-bot/auto-remediation
        delete-branch: true

    - name: Auto-merge PR
      if: github.event_name != 'pull_request'
      run: |
        gh pr merge --auto --merge
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
